"""empty message

Revision ID: f67a34d0ecef
Revises: 173f2a08535a
Create Date: 2020-10-22 15:52:19.018663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67a34d0ecef'
down_revision = '173f2a08535a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('past', sa.Boolean(), nullable=False))
    op.add_column('Shows', sa.Column('upcoming', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('Shows', 'upcoming')
    op.drop_column('Shows', 'past')

    # ### end Alembic commands ###
